theme: jekyll-theme-minimal
title: SnowActivist
description: Don't waste your time waiting in line!
logo: ![SnowActivistIcon](https://user-images.githubusercontent.com/72878620/102080320-8d899380-3e0e-11eb-8c72-59f903f94f64.png)
