theme: jekyll-theme-minimal
title: SnowActivist
description: Don't waste your time waiting in line!
logo: ![](https://github.com/gxc-international-innovation-challenge/gxc-team-23/blob/main/TeamUploads/SnowActivistIcon.png)

Jürgen
